### ISSUE TITLE
(Page) Idea Sandbox Page

### ISSUE THREAD

**Issue by alizul01** [alizul01/polinema-innovation-tribe#11]
# Help Wanted

I need to make **Idea Sandbox page** to contain all of creative idea from students, it is required to :

1. Contain Searchbar, filter by something, create idea button
2. Fetch all idea from the database (for temporary use dummy data)
3. Show all idea but only 10 - 15 idea with pagination per page? so it will boost the performance
4. Continue from num 2, when the idea clicked it will show the details page (i'll explain details page later, lets focus to idea sandbox)

**Comment by elianiva** [comment]
ini assign aja ke aku
ntar pake react-query buat data fetching, sekalian aku pasangin error boundary sama suspense

**Comment by alizul01** [comment]
Oke boleh pake react-query aja soalnya lebih optimal ya buat cachingnya
