### ISSUE TITLE
Setup project with React, Vite, TypeScript, Tailwind CSS, and Pnpm

### ISSUE THREAD

**Issue by alizul01** [alizul01/polinema-innovation-tribe#14]
## Welcome to the Polinema Innovation Tribe project! 

In this first issue, we will set up the project with these tools:

- React: a popular JavaScript library for building user interfaces
- Vite: a fast and lightweight development build tool for modern web apps
- TypeScript: a typed superset of JavaScript that adds optional static typing to the language
- Tailwind CSS: a utility-first CSS framework for rapidly building custom designs
- Pnpm: a fast and efficient package manager for Node.js

To get started, follow these steps:

1. Fork this repository and clone it to your local machine. Don't know how to fork? Well, check top right corner bestie
2. Install Pnpm by running `npm install -g pnpm` (or `yarn global add pnpm` if you prefer Yarn)
3. Run `pnpm install` to install the project dependencies
4. Run `pnpm run dev` to start the development server
5. Your task is to complete the setup process and ensure that the project is running correctly on your local machine. If you run into any issues or have questions, feel free to ask for help in the comments.

Once you have the project up and running, take a moment to **explore the code and familiarize yourself with the project structure.** When you're ready, you can start working on the next issue or suggest your own ideas for improving the project.

Thanks for contributing to the Polinema Innovation Tribe project!

**Comment by Rengkat** [comment]
Hello, i want to be part of this.

**Comment by Alessandro-Battiato** [comment]
Greetings!
Can I ask you exactly what does this project consist of?

**Comment by alizul01** [comment]
> Greetings! Can I ask you exactly what does this project consist of?

Hi there! @Alessandro-Battiato and @Rengkat , This project is about collecting creative ideas from students that will later be uploaded to the system. Afterwards, other students can view the creative ideas of others and join a team if they are compatible with the student's idea.
