### ISSUE TITLE
(FE) Login Page

### ISSUE THREAD

**Issue by alizul01** [alizul01/polinema-innovation-tribe#24]
**Login and Register Page**
We need an authentication page for login and registering the user, I'll create the design first!

Login should contain

- [x] Title
- [x] Email
- [x] Password
- [x] Forget password?
- [x] Login Button
- [x] #25
- [x] Don't have account? Register now!
- [x] Terms and Condition
- [x] tsParticles for background

![image](https://user-images.githubusercontent.com/62384197/210170419-ec10f7f8-9e96-4f26-9fb8-a9263381332f.png)

**Comment by alizul01** [comment]
@elianiva cha, any idea biar backgroundnya ngga item doang? aku kepikiran dikasih tsParticles biar keliatan asik aja

**Comment by alizul01** [comment]
Register Page

- [ ] First Name, Last Name
- [ ] Username
- [ ] Email
- [ ] Phone Number
- [ ] Password
- [ ] Confirm Password
- [ ] Password Protection (e.g. What color do you like? -- it's opsional)
- [ ] Register Button
- [ ] Already have an account? Login now!
- [ ] Terms and Condition

**Comment by elianiva** [comment]
dibikin kaya webnya ini aja
- https://turbo.build/
- https://ultrapkg.dev/
- https://stitches.dev/

jadi mereka itu kaya pake glow 2 warna gitu, soalnya kalo partikel udah banyak yg pake rasanya

**Comment by alizul01** [comment]
Glow ya? tadi sempet kebesit pake glow, keknya lebih menarik

i'll tryy 🤩
